### ISSUE TITLE
Judge crashes on invallid html

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/judge-html#221]
Eg: https://dodona.ugent.be/en/submissions/10979465/
This code results in a crash of the judge:
```html
<ol>
    <li>Fruit</li>
    <ul>
        <li id="apple">Appel</li>
        <li>Peer</li>
    </ul>
    <li><a href="groenten.html">Groenten</a></li>
</ol>
```
This does not:
```html
<ol>
    <li>Fruit
    <ul>
        <li id="apple">Appel</li>
        <li>Peer</li>
    </ul>
    </li>
    <li><a href="groenten.html">Groenten</a></li>
</ol>
```

The error:
```
Traceback (most recent call last):
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/html_judge.py", line 112, in <module>
    main()
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/html_judge.py", line 80, in main
    failed_tests += suite.evaluate(config.translator)
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/checks.py", line 1202, in evaluate
    return super().evaluate(translator)
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/checks.py", line 1095, in evaluate
    test_case.accepted = item.evaluate(self._bs, lang_abr)
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/checks.py", line 779, in evaluate
    if not self._process_one(check, bs, language):
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/checks.py", line 766, in _process_one
    return check.callback(bs)
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/checks.py", line 594, in _inner
    prop_value = self._find_css_property(prop, allow_inheritance, pseudo)
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/checks.py", line 557, in _find_css_property
    return self._css_validator.find(self._element, prop, pseudo)
  File "/mnt/tiV8yzdIgKlL2fPM8M305A/judge/validators/css_validator.py", line 354, in find
    raise AmbiguousXpath()
validators.css_validator.AmbiguousXpath
```

This error is the same as in #209

Expected behaviour would be that the judge gives an invalid html notice to the user (instead of crashing).

**Comment by BTWS2** [comment]
- https://naos.ugent.be/nl/courses/65/series/663/activities/1390525703/
- https://github.ugent.be/brewille/oef_websites/tree/master/test_judge_exercises/invalid_html
- [ ] https://naos.ugent.be/nl/submissions/983328/ (`ol` or `ul` not in `li`)
- [ ] https://naos.ugent.be/nl/submissions/983327/ (student number not in comments)

**Comment by bmesuere** [comment]
It might well be that the html in question is invalid, but the judge should _never_ crash so I would propose trying to catch the exception if it is prone to crashing. 

If the judge crashes, it generates an internal error which it should never do unless in case of catastrophic failure. For this reason, all internal errors are logged via email and in our internal slack channel.
